/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;

/**
 *
 * @author MARIO
 */
public class Formulario extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
        CentrosdeMasayCentroides contenido = new CentrosdeMasayCentroides();
        contenido.setSize(760,700);
        contenido.setLocation(0,0);
        
        content.removeAll();
        content.add(contenido, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        //Método para centrar la ventana
        centreWindow(this);
    }

    //Metodo para centrar la ventana
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuLateral = new javax.swing.JPanel();
        btnCentrosMasaYCentroides = new javax.swing.JPanel();
        txtCentrosMasayCentroides = new javax.swing.JLabel();
        btnIntegracionPorSustitucion = new javax.swing.JPanel();
        txtIntegracionPorSustitucion = new javax.swing.JLabel();
        btnFuerzayPresion = new javax.swing.JPanel();
        txtFuerzayPresion = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setPreferredSize(new java.awt.Dimension(1040, 750));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(239, 75, 76));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/btnClose.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/btnMini.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/btnReturn.png"))); // NOI18N
        jLabel1.setText("  REGRESAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÁLCULO II - FORMULARIO");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(279, 279, 279)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMinimize)
                    .addComponent(btnClose)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        menuLateral.setBackground(new java.awt.Color(239, 75, 76));

        btnCentrosMasaYCentroides.setBackground(new java.awt.Color(52, 177, 208));
        btnCentrosMasaYCentroides.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCentrosMasaYCentroides.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCentrosMasaYCentroidesMouseClicked(evt);
            }
        });

        txtCentrosMasayCentroides.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCentrosMasayCentroides.setForeground(new java.awt.Color(255, 255, 255));
        txtCentrosMasayCentroides.setText("Centros de masa y Centroides");
        txtCentrosMasayCentroides.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnCentrosMasaYCentroidesLayout = new javax.swing.GroupLayout(btnCentrosMasaYCentroides);
        btnCentrosMasaYCentroides.setLayout(btnCentrosMasaYCentroidesLayout);
        btnCentrosMasaYCentroidesLayout.setHorizontalGroup(
            btnCentrosMasaYCentroidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCentrosMasaYCentroidesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCentrosMasayCentroides)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btnCentrosMasaYCentroidesLayout.setVerticalGroup(
            btnCentrosMasaYCentroidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCentrosMasaYCentroidesLayout.createSequentialGroup()
                .addComponent(txtCentrosMasayCentroides, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnIntegracionPorSustitucion.setBackground(new java.awt.Color(52, 177, 208));
        btnIntegracionPorSustitucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntegracionPorSustitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIntegracionPorSustitucionMouseClicked(evt);
            }
        });

        txtIntegracionPorSustitucion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtIntegracionPorSustitucion.setForeground(new java.awt.Color(255, 255, 255));
        txtIntegracionPorSustitucion.setText("Integración por Sustitución");
        txtIntegracionPorSustitucion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnIntegracionPorSustitucionLayout = new javax.swing.GroupLayout(btnIntegracionPorSustitucion);
        btnIntegracionPorSustitucion.setLayout(btnIntegracionPorSustitucionLayout);
        btnIntegracionPorSustitucionLayout.setHorizontalGroup(
            btnIntegracionPorSustitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIntegracionPorSustitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIntegracionPorSustitucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnIntegracionPorSustitucionLayout.setVerticalGroup(
            btnIntegracionPorSustitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIntegracionPorSustitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIntegracionPorSustitucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFuerzayPresion.setBackground(new java.awt.Color(52, 177, 208));
        btnFuerzayPresion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFuerzayPresion.setPreferredSize(new java.awt.Dimension(247, 47));
        btnFuerzayPresion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuerzayPresionMouseClicked(evt);
            }
        });

        txtFuerzayPresion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFuerzayPresion.setForeground(new java.awt.Color(255, 255, 255));
        txtFuerzayPresion.setText("Fuerza y Presión");
        txtFuerzayPresion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnFuerzayPresionLayout = new javax.swing.GroupLayout(btnFuerzayPresion);
        btnFuerzayPresion.setLayout(btnFuerzayPresionLayout);
        btnFuerzayPresionLayout.setHorizontalGroup(
            btnFuerzayPresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFuerzayPresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFuerzayPresion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnFuerzayPresionLayout.setVerticalGroup(
            btnFuerzayPresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFuerzayPresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFuerzayPresion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCentrosMasaYCentroides, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnIntegracionPorSustitucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFuerzayPresion, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addComponent(btnCentrosMasaYCentroides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIntegracionPorSustitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFuerzayPresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 547, Short.MAX_VALUE))
        );

        bg.add(menuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 700));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 760, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Principal inicio = new Principal();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnCentrosMasaYCentroidesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCentrosMasaYCentroidesMouseClicked
        CentrosdeMasayCentroides contenido = new CentrosdeMasayCentroides();
        contenido.setSize(760,700);
        contenido.setLocation(0,0);
        
        content.removeAll();
        content.add(contenido, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCentrosMasaYCentroidesMouseClicked

    private void btnIntegracionPorSustitucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntegracionPorSustitucionMouseClicked
        IntegracionPorSustitucion integracionSustitucion = new IntegracionPorSustitucion();
        integracionSustitucion.setSize(760,700);
        integracionSustitucion.setLocation(0,0);
        
        content.removeAll();
        content.add(integracionSustitucion, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnIntegracionPorSustitucionMouseClicked

    private void btnFuerzayPresionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuerzayPresionMouseClicked
        PresionFuerza pF = new PresionFuerza();
        pF.setSize(760,700);
        pF.setLocation(0,0);
        
        content.removeAll();
        content.add(pF, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnFuerzayPresionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCentrosMasaYCentroides;
    private javax.swing.JLabel btnClose;
    private javax.swing.JPanel btnFuerzayPresion;
    private javax.swing.JPanel btnIntegracionPorSustitucion;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JLabel txtCentrosMasayCentroides;
    private javax.swing.JLabel txtFuerzayPresion;
    private javax.swing.JLabel txtIntegracionPorSustitucion;
    // End of variables declaration//GEN-END:variables
}
