/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project;

/**
 *
 * @author MARIO
 */
public class NotacionSigma extends javax.swing.JPanel {

    /**
     * Creates new form NotacionSigma
     */
    public NotacionSigma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Lbl4 = new javax.swing.JLabel();
        Lbl5 = new javax.swing.JLabel();
        Lbl6 = new javax.swing.JLabel();
        Lbl7 = new javax.swing.JLabel();
        Lbl8 = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        Lbl1 = new javax.swing.JLabel();
        LblSup1 = new javax.swing.JLabel();
        LblInf1 = new javax.swing.JLabel();
        LblSup2 = new javax.swing.JLabel();
        Lbl2 = new javax.swing.JLabel();
        LblInf2 = new javax.swing.JLabel();
        Lbl9 = new javax.swing.JLabel();
        Lbl10 = new javax.swing.JLabel();
        Lbl11 = new javax.swing.JLabel();
        Lbl12 = new javax.swing.JLabel();
        Lbl13 = new javax.swing.JLabel();
        Lbl14 = new javax.swing.JLabel();
        Lbl15 = new javax.swing.JLabel();
        Lbl16 = new javax.swing.JLabel();
        Lbl17 = new javax.swing.JLabel();
        Lbl18 = new javax.swing.JLabel();
        Lbl19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TxtLimS = new javax.swing.JTextField();
        TxtLimI = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        TxtV1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TxtV2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(860, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl3.setText("Δx=(b-a)/n");
        add(Lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("a = -1");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("b = 3");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        Lbl4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl4.setText("f(x)=(x²+6x+3)dx");
        add(Lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        Lbl5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl5.setText("f(a+kΔx) -> f(-1+k(4/n)) = f(-1+4k/n)");
        add(Lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Lbl6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl6.setText("(-1+4k/n)²+6(-1+4k/n)+3");
        add(Lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        Lbl7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl7.setText("(1+16k²/n²-8k/n)+(-6+24k/n)+3");
        add(Lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        Lbl8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl8.setText("16k²/n²+16k/n-2");
        add(Lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Label1.setText("NOTACIÓN SIGMA");
        add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        Lbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl1.setText("∫  (x²+6x+3)dx");
        add(Lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        LblSup1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblSup1.setText("3");
        add(LblSup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 15, 14));

        LblInf1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblInf1.setText("-1");
        add(LblInf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 15, 14));

        LblSup2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblSup2.setText("3");
        add(LblSup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 15, 14));

        Lbl2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl2.setText("∫ f(x)dx = lim n->∞∑ f(a+kΔx)Δx");
        add(Lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        LblInf2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblInf2.setText("-1");
        add(LblInf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 15, 14));

        Lbl9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl9.setText("∑(16k²/n²+16k/n-2)(4/n)");
        add(Lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        Lbl10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl10.setText("∑(64k²/n³+64K/n²-8/n)");
        add(Lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        Lbl11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl11.setText("∑64k²/n³+∑64K/n²-∑8/n");
        add(Lbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        Lbl12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl12.setText("64/n³∑k²+64/n²∑K-8/n∑1");
        add(Lbl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        Lbl13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl13.setText("64/n³(n(n+1)(2n+1)/6)+64/n²(n(n+1)/2)-(8/n)(n)");
        add(Lbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        Lbl14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl14.setText("64/6(n(n+1)(2n+1)/n³)+64/2(n(n+1)/n²)-8");
        add(Lbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        Lbl15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl15.setText("lim n->∞ (64/6(2n²+3n+1)/2+64/2(n+1)/n-8)");
        add(Lbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        Lbl16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl16.setText("lim n->∞ 64/6(2n²+3n+1)/2 + lim n->∞64/2(n+1)/n -  lim n->∞ 8");
        add(Lbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        Lbl17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl17.setText("64/6 lim n->∞ (2n²+3n+1)/2 +64/2 lim n->∞(n+1)/n - 8");
        add(Lbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        Lbl18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lbl18.setText("64/6(2)+64/2(1)-8");
        add(Lbl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        Lbl19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lbl19.setText("=45");
        add(Lbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));
        add(TxtLimS, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 29, -1));
        add(TxtLimI, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 29, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("(x²+");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        TxtV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtV1ActionPerformed(evt);
            }
        });
        add(TxtV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 25, 29));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("x+");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        TxtV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtV2ActionPerformed(evt);
            }
        });
        add(TxtV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 25, 29));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(")dx");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("∫");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(52, 177, 208));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(52, 177, 208));
        jButton1.setText("Calcular");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 320, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtV1ActionPerformed

    private void TxtV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtV2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int limsup,liminf,num1,num2,deltx,c1,deltc,ps2,t2,con;
        String signo;
        limsup = Integer.parseInt(TxtLimS.getText());
        liminf = Integer.parseInt(TxtLimI.getText());
        num1 = Integer.parseInt(TxtV1.getText());
        num2 = Integer.parseInt(TxtV2.getText());
        deltx=limsup-liminf;
        c1=liminf*liminf;
        deltc=deltx*deltx;
        ps2=liminf*deltx*2;
        t2=(ps2)+(num1*deltx);
        con=c1+num2+(num1*liminf);
        int f1,f2,f3;
        f1=deltc*deltx;
        f2=t2*deltx;
        f3=con*deltx;
        if(liminf>0)
        {
            signo="-";
        }else
        {
            signo="+";
        }
        LblSup1.setText(TxtLimS.getText());
        LblInf1.setText(TxtLimI.getText());
        LblSup2.setText(TxtLimS.getText());
        LblInf2.setText(TxtLimI.getText());
        Lbl1.setText("∫  (x²+"+num1+"x+"+num2+")dx");
        Lbl2.setText("∫ f(x)dx = lim n->∞∑ f("+liminf+"+kΔx)Δx");
        Lbl3.setText("Δx=("+liminf+"-"+limsup+")/n");
        Lbl4.setText("f(x)=(x²+"+num1+"x+"+num2+")dx");
        Lbl5.setText("f(a+kΔx) -> f("+liminf+"+k("+deltx+"/n)) = f("+liminf+"+"+deltx+"k/n)");
        Lbl6.setText("("+liminf+"+"+deltx+"k/n)²+"+num1+"("+liminf+"+"+deltx+"k/n)+"+num2);
        Lbl7.setText("("+c1+"+"+deltc+"k²/n²"+signo+ps2+"k/n)+("+num1*liminf+"+"+num1*deltx+"k/n)+"+num2);
        Lbl8.setText(deltc+"k²/n²+"+t2+"k/n-"+con);
        Lbl9.setText("∑("+deltc+"k²/n²+"+t2+"k/n"+con+")("+deltx+"/n)");
        Lbl10.setText("∑("+f1+"k²/n³+"+f2+"K/n²-"+f3+"/n)");
        Lbl11.setText("∑"+f1+"k²/n³+∑"+f2+"K/n²+∑"+f3+"/n");
        Lbl12.setText(f1+"/n³∑k² + "+f2+"/n²∑K + "+f3+"/n∑1");
        Lbl13.setText(f1+"/n³(n(n+1)(2n+1)/6) + "+f2+"/n²(n(n+1)/2) + ("+f3+"/n)(n)");
        Lbl14.setText(f1+"/6(n(n+1)(2n+1)/n³) + "+f2+"/2(n(n+1)/n²)+"+f3);
        Lbl15.setText("lim n->∞ ("+f1+"/6(2n²+3n+1)/2 + "+f2+"/2(n+1)/n + "+f3+")");
        Lbl16.setText("lim n->∞ "+f1+"/6(2n²+3n+1)/2 + lim n->∞ "+f2+"/2(n+1)/n +  lim n->∞ "+f3);
        Lbl17.setText(f1+"/6 lim n->∞ (2n²+3n+1)/2 + "+f2+"/2 lim n->∞(n+1)/n + "+f3);
        Lbl18.setText(f1+"/6(2) + "+f2+"/2(1) + "+f3);
        Lbl19.setText("= "+((f1/6)*2+(f2/2)+f3));
        jLabel9.setText("a= "+TxtLimS.getText());
        jLabel10.setText("b= "+TxtLimI.getText());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl10;
    private javax.swing.JLabel Lbl11;
    private javax.swing.JLabel Lbl12;
    private javax.swing.JLabel Lbl13;
    private javax.swing.JLabel Lbl14;
    private javax.swing.JLabel Lbl15;
    private javax.swing.JLabel Lbl16;
    private javax.swing.JLabel Lbl17;
    private javax.swing.JLabel Lbl18;
    private javax.swing.JLabel Lbl19;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel Lbl4;
    private javax.swing.JLabel Lbl5;
    private javax.swing.JLabel Lbl6;
    private javax.swing.JLabel Lbl7;
    private javax.swing.JLabel Lbl8;
    private javax.swing.JLabel Lbl9;
    private javax.swing.JLabel LblInf1;
    private javax.swing.JLabel LblInf2;
    private javax.swing.JLabel LblSup1;
    private javax.swing.JLabel LblSup2;
    private javax.swing.JTextField TxtLimI;
    private javax.swing.JTextField TxtLimS;
    private javax.swing.JTextField TxtV1;
    private javax.swing.JTextField TxtV2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
