/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project;

/**
 *
 * @author MARIO
 */
public class PresionFuerza extends javax.swing.JPanel {

    /**
     * Creates new form PresionFuerza
     */
    public PresionFuerza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label5 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Label10 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(760, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label5.setText("Fuerza y Presión");
        add(Label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        Label3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label3.setForeground(new java.awt.Color(255, 255, 255));
        Label3.setText("F =( fuerza por unidad de área) * (área de superficie)");
        add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        Label12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label12.setForeground(new java.awt.Color(255, 255, 255));
        Label12.setText("F = phA");
        add(Label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        Label6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Label6.setText("Presión del Fluido");
        add(Label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(52, 177, 208));

        Label10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label10.setForeground(new java.awt.Color(255, 255, 255));
        Label10.setText("F = (presión del fluido) * (área de superficie)");

        Label4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label4.setForeground(new java.awt.Color(255, 255, 255));
        Label4.setText("F = PA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label4)
                    .addComponent(Label10))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(Label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label10)
                .addGap(67, 67, 67))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 650, 190));

        jPanel2.setBackground(new java.awt.Color(52, 177, 208));

        Label7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label7.setForeground(new java.awt.Color(255, 255, 255));
        Label7.setText("P=(peso por unidad de volúmen) * (profundidad) ");

        Label8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label8.setForeground(new java.awt.Color(255, 255, 255));
        Label8.setText("P = ph");

        Label2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label2.setForeground(new java.awt.Color(255, 255, 255));
        Label2.setText("Fuerza ejercida por un Fluido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label2)
                    .addComponent(Label8)
                    .addComponent(Label7))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label7)
                .addGap(13, 13, 13)
                .addComponent(Label8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 650, 160));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
